name: keycloakify-test
on:
  push:
    branches:
      - main
concurrency:
  group: ci-${{ github.ref == 'refs/heads/main' && github.run_id || github.ref }}-keycloak-test
  cancel-in-progress: true
jobs:
  keycloakify-test:
    name: Test keycloakify local builds
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 'v22'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build
      - name: Build storybook
        run: yarn build-storybook
      - name: Build keycloak theme
        run: yarn build-keycloak-theme
